baseURL = "https://www.raffaelespataro.it/"
title = "Raffaele Spataro"


# themesDir = "themes/m10c" -raf

theme = "m10c"

paginate = 5

publishDir = "docs"
contentDir = "content"
defaultContentLanguage = "it"
enableEmoji = "true"
enableGitInfo = "true"

# https://https-www-raffaelespataro-it.disqus.com/admin/settings/general/ -raf
disqusShortname = "https-www-raffaelespataro-it"

# put custom variables here! -raf
[params]
  author = "Raffaele Spataro"
  description = "Per gli amici Raffa. Appassionato di datascience, programmazione e filosofia. Credo in un futuro digitale e senza pregiudizi."
  avatar = "avataaars.png"
  myvar1 = "Post recenti"
  
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/raffaele-spataro-44194b57/"
  [[params.social]]
    name = "github"
    url = "https://github.com/raphael2692"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/raffaele2692"


  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"

[params.style]
    primaryColor = "#990d44"