baseURL = "https://www.raffaelespataro.it/"
title = "Il mio Blog"

# themesDir = "../.."

theme = "m10c"

paginate = 5

publishDir = "docs"
contentDir = "content"
defaultContentLanguage = "it"
enableEmoji = "true"
enableGitInfo = "true"

disqusShortname = "raffaelespataro"

[params]
  author = "Raffaele Spataro"
  description = "Per gli amici Raffa. Appassionato di data science, programmazione e filosofia. Credo in un futuro digitale e senza pregiudizi."
  avatar = "avataaars.png"
  
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/raffaele-spataro-44194b57/"
  [[params.social]]
    name = "github"
    url = "https://github.com/raphael2692"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/raffaele2692"


  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"

[params.style]
    primaryColor = "#990d44"